files:
  - source: '**/*.md'
    ignore:
      - '**/final_state.md'
      - '**/initial_state.md'
    translation: /%locale%/%original_path%/%original_file_name%
  - source: '**/*.yml'
    ignore:
      - '**/test.yml'
    translation: /%locale%/%original_path%/%original_file_name%
