---
locale: es
tags: [ ]
layout: input_kids
editor: custom
type: problem
extra_visible: false
teacher_info: "Cada programa que hacemos está pensado para una situación determinada. Eso significa que considera (o no) características del tablero, los bloques disponibles, las restricciones o demandas del enunciado, entre otras cosas.\nYa recomendamos analizar un poco de qué se trata el desafío antes de empezar a programar. Esta actividad particularmente nos ayuda a pensar en un aspecto **muy importante** cuando tenemos un tablero para recorrer. Para pensar: \n\n* ¿Cuál es el punto de partida? \n* ¿Mi programa cumplirá el objetivo sin importar dónde se encuentre Mukinita? \n* ¿El primer paso para resolver este problema requiere ubicarme en una posición determinada?"
manual_evaluation: false
choices: [ ]
name: "...y a veces se pierde"
